# Generated by Django 4.2 on 2023-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('imagen1', models.CharField(blank=True, max_length=254)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_disponible', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
    ]
